<h2><?php echo __('Setting Up a Custom Homepage (Pro only)', 'the-authority'); ?></h2>
<p><?php echo __('The Authority Pro let&#8217;s you create a custom homepage with a featured banner and section panels featuring content from other pages.', 'the-authority'); ?></p>
<h3><?php echo __('Creating the Homepage', 'the-authority'); ?></h3>
<p><?php echo __('To create the homepage you&#8217;ll need to create a new homepage and select the ', 'the-authority'); ?><strong><?php echo __('Homepage ', 'the-authority'); ?></strong><?php echo __('template.', 'the-authority'); ?></p>
<p><?php echo __('You&#8217;ll then need to set this as your front page under ', 'the-authority'); ?><strong><?php echo __('Settings &gt; Reading ', 'the-authority'); ?></strong><?php echo __('and selecting ', 'the-authority'); ?><strong><?php echo __('A static page', 'the-authority'); ?></strong><?php echo __(' then setting the newly created page as your ', 'the-authority'); ?><strong><?php echo __('Homepage.', 'the-authority'); ?></strong></p>
<h3><?php echo __('Setting up the featured banner', 'the-authority'); ?></h3>
<p><?php echo __('The featured banner pulls in the featured image and content from the page using your ', 'the-authority'); ?><strong><?php echo __('Homepage ', 'the-authority'); ?></strong><?php echo __('template.', 'the-authority'); ?></p>
<p><img class="aligncenter size-full wp-image-251" src="<?php echo get_stylesheet_directory_uri(); ?>/inc/admin/getting-started/images/the-authority-pro-homepage.jpg" alt="The Authority Pro Homepage" width="1284" height="557" /></p>
<p><?php echo __('You can also adjust the appearance of the featured banner from the customizer. Navigate to ', 'the-authority'); ?><strong><?php echo __('Appearance &gt; Customize', 'the-authority'); ?></strong><?php echo __(' and select the ', 'the-authority'); ?><strong><?php echo __('Header Image ', 'the-authority'); ?></strong><?php echo __('panel.', 'the-authority'); ?></p>
<p><?php echo __('At the bottom of the panel you&#8217;ll see settings for ', 'the-authority'); ?><strong><?php echo __('Header Alignment', 'the-authority'); ?></strong><?php echo __(' and ', 'the-authority'); ?><strong><?php echo __('Header Width Ratio.', 'the-authority'); ?></strong></p>
<p><?php printf( __( '<a href="%1$s" target="_blank">Video Example</a>', 'the-authority'), 'https://www.youtube.com/embed/olM729BlYGE'); ?></p>
<h3><?php echo __('Setting Up Homepage Panels', 'the-authority'); ?></h3>
<p><?php echo __('To pull in other page content into your homepage panel navigate to the cusotmizer at ', 'the-authority'); ?><strong><?php echo __('Appearance &gt; Customizer ', 'the-authority'); ?></strong><?php echo __('then open the ', 'the-authority'); ?><strong><?php echo __('Theme Options &gt; Front Page Sections ', 'the-authority'); ?></strong><?php echo __('panel.', 'the-authority'); ?></p>
<p><?php echo __('From here you can easily select any page to display content in your homepage sections.', 'the-authority'); ?></p>
<p><?php echo __('Some templates will pull in custom information. If you want to pull in your posts select your page used as your ', 'the-authority'); ?><strong><?php echo __('Page for Posts', 'the-authority'); ?></strong><?php echo __(' in your ', 'the-authority'); ?><strong><?php echo __('Settings &gt; Reading', 'the-authority'); ?></strong><?php echo __(' section. For WooCommerce products select the page used as your Shop in your WooCommerce settings.', 'the-authority'); ?></p>
<p><?php printf( __('<a href="%1$s" target="_blank">Video Example</a>', 'the-authority'), 'https://www.youtube.com/embed/EEDeORn4Q20'); ?></p>
<h2 id="jetpack"><?php echo __('Setting Up Jetpack', 'the-authority'); ?></h2>
<p><?php echo __('After installing and activating the Jetpack plugin you\'ll be asked to connect to a ', 'the-authority'); ?><a href="http://WordPress.com"><?php echo __('WordPress.com', 'the-authority'); ?></a><?php echo __(' account to enable the Jetpack features. Upon doing so you’ll need to enable the individual features you’d like to use. Zuul is tuned to use the following items:', 'the-authority'); ?></p>
<ul>
<li><b><?php echo __('Testimonials', 'the-authority'); ?></b><?php echo __(' and ', 'the-authority'); ?><b><?php echo __('Portfolios', 'the-authority'); ?></b><?php echo __(' can be individually activated under the ', 'the-authority'); ?><b><?php echo __('Writing', 'the-authority'); ?></b><?php echo __(' section within the ', 'the-authority'); ?><b><?php echo __('Custom content types', 'the-authority'); ?></b><?php echo __(' meta box.', 'the-authority'); ?></li>
<li><b><?php echo __('Infinite Scrolling', 'the-authority'); ?></b><?php echo __(' can be turned on under the ', 'the-authority'); ?><b><?php echo __('Writing', 'the-authority'); ?></b><?php echo __(' section within the ', 'the-authority'); ?><b><?php echo __('Theme enhancements', 'the-authority'); ?></b><?php echo __(' meta box.', 'the-authority'); ?></li>
<li><b><?php echo __('Tiled galleries', 'the-authority'); ?></b><?php echo __(' can be activated by turning on the ', 'the-authority'); ?><b><?php echo __('Speed up images and photos', 'the-authority'); ?></b><?php echo __(' setting in the ', 'the-authority'); ?><b><?php echo __('Media', 'the-authority'); ?></b><?php echo __(' metabox. This also offloads images to the ', 'the-authority'); ?><a href="http://WordPress.com"><?php echo __('WordPress.com', 'the-authority'); ?></a><?php echo __(' servers which can speed up your site. Alternatively ', 'the-authority'); ?><b><?php echo __('Tiled galleries', 'the-authority'); ?></b><?php echo __(' can be turned on individually by going to ', 'the-authority'); ?><a href="http://yourdomain.com/wp-admin/admin.php?page=jetpack_modules"><?php echo __('yourdomain.com/wp-admin/admin.php?page=jetpack_modules', 'the-authority'); ?></a></li>
</ul>
<p><?php echo __('There are many additional feature within Jetpack that can be used to improve social sharing, related posts, stats, and more.', 'the-authority'); ?></p>
<h2 id="woocommerce"><?php echo __('Setting Up WooCommerce (Pro Only)', 'the-authority'); ?></h2>
<p><?php echo __('The Authority Pro supports the WooCommerce plugin that allows you to easily sell digital and physical goods from your WordPress site.', 'the-authority'); ?></p>
<p><?php echo __('After installing and activating the plugin WooCommerce will walk you through a guide to set up your store and create your first products.', 'the-authority'); ?></p>
<p><b><?php echo __('Note:', 'the-authority'); ?></b><?php echo __(' While not required it is recommended to use the ', 'the-authority'); ?><b><?php echo __('Full Width', 'the-authority'); ?></b><?php echo __(' page template for the Cart and Checkout pages.', 'the-authority'); ?></p>
<p><?php echo __('The Authority Pro does support widgets for the Shop page on your site. To learn more about adding widgets check the ', 'the-authority'); ?><a href="#adding-widgets-to-sidebars"><?php echo __('Widgets', 'the-authority'); ?></a><?php echo __(' section of this guide.', 'the-authority'); ?></p>
<p><?php echo __('For more information on WooCommerce check out their extremely useful ', 'the-authority'); ?><a href="https://docs.woocommerce.com/documentation/plugins/woocommerce/"><?php echo __('documentation', 'the-authority'); ?></a></p>
<h2><?php echo __('Custom Menus', 'the-authority'); ?></h2>
<p><?php echo __('The Authority comes with several custom menu locations.', 'the-authority'); ?></p>
<p><strong><?php echo __('Primary Menu', 'the-authority'); ?></strong><?php echo __(' &#8211; The main navigation for your site. Supports multiple levels of menu items via a dropdown. Automatically turns into a slide out menu at mobile screen sizes.', 'the-authority'); ?></p>

<p><?php echo __('&nbsp;', 'the-authority'); ?></p>
<p><?php echo __('Draw focus by adding the ', 'the-authority'); ?><code><?php echo __('callout-nav', 'the-authority'); ?></code><?php echo __(' class to your menu items.', 'the-authority'); ?></p>
<p><img class="aligncenter size-full wp-image-25367" src="<?php echo get_stylesheet_directory_uri(); ?>/inc/admin/getting-started/images/callout-nav-menu.png" alt="Callout Nav Class" width="416" height="336" /></p>
<p><strong><?php echo __('Secondary Menu', 'the-authority'); ?></strong><?php echo __(' &#8211; Support for a secondary menu with multiple levels. As well as custom search. Secondary menu also displays a cart icon when Easy Digital Downloads is in use.', 'the-authority'); ?></p>
<p><img class="aligncenter size-full wp-image-25368" src="<?php echo get_stylesheet_directory_uri(); ?>/inc/admin/getting-started/images/authority-menu.png" alt="Authority Menu" width="1236" height="134" /></p>
<p><strong><?php echo __('Footer Menu', 'the-authority'); ?></strong><?php echo __(' &#8211; Set up a custom menu to display in your footer.', 'the-authority'); ?></p>
<h2><?php echo __('Widget Areas', 'the-authority'); ?></h2>
<p><img class="alignright wp-image-25359 size-large" src="<?php echo get_stylesheet_directory_uri(); ?>/inc/admin/getting-started/images/widget-areas-370x1024.png" alt="The Authority Widgetized Areas" width="370" height="1024" /><?php echo __('The Authority comes with several widgetized areas so you can make use of any of the great ', 'the-authority'); ?><?php echo __('widgets offered by WordPress', 'the-authority'); ?><?php echo __(' or plugins.', 'the-authority'); ?></p>
<p><strong><?php echo __('Sidebar ', 'the-authority'); ?></strong><?php echo __('&#8211; Add widgets to the sidebar on the homepage and any Page using the ', 'the-authority'); ?><strong><?php echo __('Page with Sidebar', 'the-authority'); ?></strong><?php echo __(' template.', 'the-authority'); ?></p>
<p><strong><?php echo __('After First Post ', 'the-authority'); ?></strong><?php echo __('&#8211; Add widgets below the first post of your main post loop. Great for calling attention to something important on your homepage.', 'the-authority'); ?></p>
<p><strong><?php echo __('Before Content ', 'the-authority'); ?></strong><?php echo __('&#8211; Add widgets before ', 'the-authority'); ?><code><?php echo __('the_content', 'the-authority'); ?></code><?php echo __(' is called on your single posts page. This displays below the thumbnail and excerpt.', 'the-authority'); ?></p>
<p><strong><?php echo __('After Content ', 'the-authority'); ?></strong><?php echo __('&#8211; Add widgets after your content to drive users further into your site.', 'the-authority'); ?></p>
<p><strong><?php echo __('Footer ', 'the-authority'); ?></strong><?php echo __('&#8211; The footer is divided into 3 widgetized areas allowing you to fully customize the content within your footer.', 'the-authority'); ?></p>
<p><strong><?php echo __('Bonus', 'the-authority'); ?></strong><strong><?php echo __(' Tip ', 'the-authority'); ?></strong><?php echo __('&#8211; Use ', 'the-authority'); ?><a href="https://wordpress.org/plugins/jetpack/" target="_blank" rel="noopener"><?php echo __('Jetpack&#8217;s', 'the-authority'); ?></a><?php echo __(' widget visibility options or ', 'the-authority'); ?><a href="https://wordpress.org/plugins/woosidebars/" target="_blank" rel="noopener"><?php echo __('WooSidebars', 'the-authority'); ?></a><?php echo __(' to control which widgets show where down to individual pages and categories.', 'the-authority'); ?></p>
<h2><?php echo __('Templates', 'the-authority'); ?></h2>
<p><strong><?php echo __('Default Template', 'the-authority'); ?></strong><?php echo __(' &#8211; The default landing page featuring title, thumbnail, content, and before and after widget areas.', 'the-authority'); ?></p>
<p><strong><?php echo __('Page with Sidebar ', 'the-authority'); ?></strong><?php echo __('&#8211; The content shifts left on this template to make use with a fully featured widgetized area on the side.', 'the-authority'); ?></p>
<p><strong><?php echo __('Page Full Width ', 'the-authority'); ?></strong><?php echo __('&#8211; The Default Template with the content spreading to the full-width of the page container.', 'the-authority'); ?></p>
<p><strong><?php echo __('Landing Page', 'the-authority'); ?></strong><?php echo __(' &#8211; A template featuring a header and footer and a blank canvas in the middle. Perfect for use with page builders like ', 'the-authority'); ?><a href="https://www.elegantthemes.com/plugins/divi-builder/" target="_blank" rel="noopener"><?php echo __('Divi', 'the-authority'); ?></a></p>
<h2><?php echo __('Customizer Support', 'the-authority'); ?></h2>
<p><?php echo __('Fully integrated with the WordPress customizer to make the theme your own.', 'the-authority'); ?></p>
<p><img class="aligncenter size-large wp-image-25362" src="<?php echo get_stylesheet_directory_uri(); ?>/inc/admin/getting-started/images/customizer-1024x520.jpg" alt="The Authority Customizer" width="640" height="325" /></p>
<h2><?php echo __('Easy Digital Downloads Support', 'the-authority'); ?></h2>
<p><?php echo __('Start selling your products online with support for ', 'the-authority'); ?><a href="https://easydigitaldownloads.com/" target="_blank" rel="noopener"><?php echo __('Easy Digital Downloads', 'the-authority'); ?></a><?php echo __(' built in to the theme. You&#8217;ll be selling digital products online in no time.', 'the-authority'); ?></p>
<p><?php echo __('The post ', 'the-authority'); ?><a rel="nofollow" href="https://www.themes.pizza/help/the-authority/"><?php echo __('The Authority', 'the-authority'); ?></a><?php echo __(' appeared first on ', 'the-authority'); ?><a rel="nofollow" href="https://www.themes.pizza"><?php echo __('Themes.Pizza', 'the-authority'); ?></a></p>
